### ISSUE TITLE
Life를 구현했는데...

### ISSUE THREAD

**Issue by good-riverdeer** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#13]
`life_riverdeer` 브랜치에 목숨을 구현했습니다...

잠시동안 공룡을 무적으로 만드는 방법을 시도했지만 시간을 다루는 것에 어려움이 있었습니다.

pygame 특성상 계속 스크립트를 읽어내는 것 같은데 그래서 시간을 기록할 수가 없었습니다.

한 번 시간을 변수에 저장하고 그 변수를 사용하려고 했지만, 계속 스크립트를 읽어내니까 그 변수에 담기는 시간이 계속 최신화가 되더라구요...

그래서 일단 충돌하면 장애물을 없애는 방법으로 했습니다. 충돌하면 선인장 그림이 없어져서 좀 모양새가 그렇습니다....

**Comment by kimbk209** [comment]
음 Dino 클래스에 **self.invincible=True** 이런식으로 변수를 하나 추가하고
cacti에 부딪혔을때 
if **playerDino.invincible==False** and life == 0:
                            playerDino.isDead = True
요런식으로 구현하면 어떨까요?

**Comment by kimbk209** [comment]
![image](https://user-images.githubusercontent.com/64012235/99150891-d7317200-26da-11eb-879d-8a13e55edc6c.png)
![image](https://user-images.githubusercontent.com/64012235/99150897-dbf62600-26da-11eb-9f00-14d56be57699.png)

**Comment by good-riverdeer** [comment]
`Dino.invincible`을 다시 False로 돌려야 하지 않나요?

**Comment by kimbk209** [comment]
맞네요.. 무적으로 만드는것만 생각하고 시간지나면 돌리는걸 생각을못했습니다

**Comment by good-riverdeer** [comment]
ㅠㅠ... 다시 돌리는게 어렵더라구요

**Comment by kimbk209** [comment]
![image](https://user-images.githubusercontent.com/64012235/99152001-727a1580-26e2-11eb-86c1-a63b28c07719.png)

**Comment by good-riverdeer** [comment]
멋집니다 병권님

근데 300의 시간은 몇초인가요?

**Comment by kimbk209** [comment]
300밀리초입니다
