### ISSUE TITLE
typescore()에 대한 질문입니다.

### ISSUE THREAD

**Issue by good-riverdeer** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#18]
![image](https://user-images.githubusercontent.com/67779236/99611941-ebb59780-2a57-11eb-94fe-ccfa448ac5e1.png)

485번째 줄에 `QUIT` 이벤트를 받으면 어떤 일을 수행하는지 알고 싶습니다.

`typescore()`가 실행되는 중에 종료 명령을 넣어도 게임이 종료되지 않는 걸 수정하려고 보니 이와같은 명령이 있길래 멈췄습니다. 어떤 명령인지 알 수 있을까요?

**Comment by kimbk209** [comment]
타이핑 도중 종료가 불가능하게하는 코드입니다 
닉네임 입력도중에 게임을 끄면 좀 이상하다고 생각이 들어서 넣은 부분인데 수정하셔도 문제없을것 같습니다

**Comment by good-riverdeer** [comment]
넵 감사합니다. 혹시 수정의 여지가 있을 수 있으니 주석처리하고 수정하도록 하겠습니다.
