### ISSUE TITLE
점프대 생성했습니다.

### ISSUE THREAD

**Issue by good-riverdeer** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#24]
나중에 이단 점프도 구현하려고 우선 issue에 진행상황 남기겠습니다.

+ `jump.png`를 추가했습니다. 이미지가 좀 깨지는 거 같은데 해결해보겠습니다.
+ `item.py`에 `HighJumpItem` 클래스를 추가했습니다.
+ 공룡이 점프대랑 충돌하면 살짝 더 뜁니다. `main.py`에 240 ~ 244 line에 구현했습니다.
+ `Dino` 클래스에 `superJumpSpeed` 변수를 추가했습니다.

+ 공룡 이미지의 이름을 바꾸었습니다.

**Comment by kimbk209** [comment]
확인했습니다

지금 jump에 구현되어있는 건가요?

**Comment by good-riverdeer** [comment]
넵넵 점프에 있습니다
