### ISSUE TITLE
`resized_screen` 변수에 대한 질문입니다.

### ISSUE THREAD

**Issue by good-riverdeer** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#29]
`main.py`의 각 함수마다 최소 창크기를 제한하는 코드에서 `resized_screen` 변수에 대해 몇몇 함수는 global로 전역변수 처리를 하고 몇몇 함수에서는 그냥 처리하시던데 특별한 이유가 있을까요?

**Comment by kimbk209** [comment]
전역변수 선언은 창모드를 구현하는 `resized_screen`을 blit할때 필요한 부분이라 적어두었습니다

없는 부분은 제가 그냥 필요없겠거니 하고 누락했는데

읽어보고 확인해보니 말씀해주신대로 그냥 처리한 부분에서는 창모드가 제대로 작동 안하더라구요

모든 함수에 필요하다고 판단되어서 `main.py`의 모든 함수에서 전역변수 선언하도록 수정했습니다
