### ISSUE TITLE
typescore()에 대한 버그입니다.

### ISSUE THREAD

**Issue by good-riverdeer** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#34]
전체화면 혹은 화면을 늘리고 진행하다가 `typescore()`에 진입하면 화면조정이 비활성화되면서 다시 최소 화면크기로 돌아갑니다.

**Comment by kimbk209** [comment]
지금 이부분을 같은문제로 세 번째 수정하고있는데 ㅠㅠ 누군가 해당부분을 예전버전으로 커밋하시는거 같습니다.. 모두들 트리새로 만드시고 나서 꾸준히 최신화 부탁드립니다

**Comment by kimbk209** [comment]
오늘중으로 한번 더 수정해놓을게요

**Comment by good-riverdeer** [comment]
아항... 넵 알겠습니다. 간단한 수정이시면 제가 올린 풀리퀘스트 브랜치에 업데이트 해주시고 이 이슈는 닫아주세요!

**Comment by kimbk209** [comment]
넵 ㅠ 제가 마침 `typescore()` 수정중이라 완료하고나서 따로 한꺼번에 풀리퀘스트 올리겠습니다
