### ISSUE TITLE
데모준비

### ISSUE THREAD

**Issue by kimbk209** [CSID-DGU/2020-2-OSSP-CP-OldKokiri-6#41]
전체화면 기능까지 메인브랜치에 반영되었습니다

이제 데모 진행 전에 해보면서 제대로 작동하지 않는 부분 찾아서 고치면 마무리가 될 것 같습니다

문제점이 발견되시면 여기 적어주시거나 단톡방에 말씀해주시면 보완을 진행하는 것으로 하겠습니다

**Comment by kiho7248** [comment]
넵
